info:
  title: Treepos API
  version: 1.0.0
  description: This is API documentation for Treepos
openapi: 3.1.0
servers:
  - url: https://pos.marstree.ltd/api
paths:
  # /orgs/{org}/repos:
  #   parameters:
  #     - in: path
  #       name: org
  #       required: true
  #       schema:
  #         type: string
  #   get:
  #     responses:
  #       "200":
  #         description: 200 response
  #         content:
  #           application/json; charset=utf-8:
  #             schema:
  #               $ref: "#/components/schemas/GetOrgsOrgRepos200ResponseBody"
  /items/list:
    get:
      parameters:
        - in: query
          name: id
          description: 貨品系統ID
          schema:
            type: string
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/GetItemsList200ResponseBody"
components:
  schemas:
    GetItemsList200ResponseBody:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
            description: 貨品系統ID
        required:
          - id
